### ISSUE TITLE
Darker cars, typically when parked, are not registered

### ISSUE THREAD

**Issue by ambroxer** [UTC-SCAL/SCAL-Infrastructure#2]
**Describe the bug**
Darker parked vehicles cease to be recognized by the camera/ assigned an ID.

**Scenario**
Black SUV parked behind smaller white car is not recognized (or when it is, it is sporadically reassigned ID's), but the white car continues to be recognized/ assigned an ID. The black car is even larger and is parked closer to the camera, yet is not assigned an ID.

**Expected behavior**
All (fully visible) parked cars within a certain distance should be tagged with an ID. 

**Screenshots**

![image](https://user-images.githubusercontent.com/48224792/53774860-295a4180-3ebe-11e9-870f-24732f33cd11.png)

**Comment by oitsjustjose** [comment]
Interesting, can you keep an eye on this and see if:
- Moving dark cars also get ignored 
- Parked light cars also get ignored at a similar / same distance
- This persists during the day or if it's just at night
- This is an issue with distance or not (i.e. closer dark parked cars at night work or not)

**Comment by ambroxer** [comment]
There is a smaller, dark car also now parked in front of it, which has an ID. It seems to be more fully illuminated by the streetlamp. It is farther from the camera, so this incident seems to be more light-based.
![image](https://user-images.githubusercontent.com/48224792/53775217-9d491980-3ebf-11e9-8157-3a73dccf0f06.png)

**Comment by oitsjustjose** [comment]
Ah I see, so it's the city's fault and we need more lighting 😛

**Comment by ambroxer** [comment]
This parked black car (on the right side of Houston) is in the full light, is closer to the camera, and keeps getting reassigned ID's. I have noticed that possibly the tracker has a harder time differentiating dark cars if their lights are off, compared to the contrast of dark headlight/tail lights on a lighter-colored car.
![image](https://user-images.githubusercontent.com/48224792/53776482-2e21f400-3ec4-11e9-8451-751d8df7a8fe.png)

**Comment by ambroxer** [comment]
Apologize if this is spam, but here is another example of another dark car parked in the same place, with tail-lights on. The tracker keeps up with it with a constant ID.
![image](https://user-images.githubusercontent.com/48224792/53776812-41818f00-3ec5-11e9-90e3-068223b24b44.png)

**Comment by ambroxer** [comment]
![image](https://user-images.githubusercontent.com/48224792/54001183-5dc93a00-4118-11e9-823d-0f3ab86eabec.png)

![image](https://user-images.githubusercontent.com/48224792/54001264-b00a5b00-4118-11e9-8d6a-4029a34d6af5.png)

This issue also occurs with lighter vehicles if they have a light backdrop, as seen by the truck parked on the right. It was reassigned an ID after having a bounding box disappear and reappear multiple times, likely because the camera was having a hard time distinguishing the features of the silver truck.

**Comment by oitsjustjose** [comment]
Moved to [here](https://github.com/ut-cuip/utc-cuip-video-event-producer/issues/5)
