### ISSUE TITLE
Two parked cars, one ID

### ISSUE THREAD

**Issue by ambroxer** [UTC-SCAL/SCAL-Infrastructure#3]
**Describe the bug**
Two consecutively parked cars count as one combined ID, as shown in the image, it combined the 2 cars into one identity and placed its bounding box between the two vehicles.

**Scenario**
Night-time, the black car is parked closely to the white truck.

**Expected behavior**
The two cars should have separate ID's.

**Screenshots**

![image](https://user-images.githubusercontent.com/48224792/53775318-19436180-3ec0-11e9-8d88-796e44fbbfc4.png)

**Comment by oitsjustjose** [comment]
This is a YOLO issue unfortunately - out of my control
