### ISSUE TITLE
Truck tagged as a motorbike

### ISSUE THREAD

**Issue by ambroxer** [UTC-SCAL/SCAL-Infrastructure#4]
**Describe the bug**
Sometimes, larger cars, especially trucks, will be recognized as motorbikes the entire time they are viewed in the camera feed.

**Scenario**
Night-time, black truck traveling east (to the left) continuously was recognized as a motorbike. It was viewed from more than one angle, but the ID did not correct itself.

**Expected behavior**
The truck should have been recognized as a car.

**Screenshots**

![image](https://user-images.githubusercontent.com/48224792/53775843-f914a200-3ec1-11e9-9bf4-178b07cd3644.png)

**Comment by oitsjustjose** [comment]
Could have to do with:

 https://github.com/UTC-SCAL/Infrastructure/blob/dc4b97943f5c6b14caeae86a9f4e05673f208334/Video/Vehicle%20Counting/sort.py#L120-L122

TODO: Start considering the **confidence** of the detection too.

**Comment by oitsjustjose** [comment]
Moved to [here](https://github.com/ut-cuip/utc-cuip-video-event-producer/issues/4)
