### ISSUE TITLE
Cars halfway into the camera view are tagged, then re-tagged as they pull into view

### ISSUE THREAD

**Issue by ambroxer** [UTC-SCAL/SCAL-Infrastructure#5]
**Describe the bug**
Cars that pull partway into the camera feed are given a label, then another vehicle obscures them momentarily and sometimes a new ID is assigned to the previous car.

**Scenario**
Night-time, a black car on the left side of the camera feed on Houston is given an ID, then the white car that is shown turning had obscured the black car. After passing by and the black car, still partially in view after being passed, is given a new ID.

**Expected behavior**
The car in partial view should be tracked consistently with a single ID. Otherwise, an ID should be assigned once the car has been fully identified or is mostly in view.

**Screenshots**

![image](https://user-images.githubusercontent.com/48224792/53846799-579e5680-3f7c-11e9-9afe-953d0ce4b699.png)

**Comment by ambroxer** [comment]
Mostly posting this for archival reasons, it is basically the same scenario, but during the day. I have noticed that cars on this feed tend to be reassigned ID's more often, I would estimate 15-20% of the time. This issue may not be easy to fix, but posting I felt that posting this issue was important to document.
The blue car turning was reassigned an ID as it reached a threshold on the screen, which is where most cars are reassigned ID's. This tends to be around the area the car is in the second image.

![image](https://user-images.githubusercontent.com/48224792/54091357-a7529880-4355-11e9-91e9-5acb71d94313.png)
![image](https://user-images.githubusercontent.com/48224792/54091359-ad487980-4355-11e9-83b1-3397bcbcb46d.png)

**Comment by oitsjustjose** [comment]
Moved to [here](https://github.com/ut-cuip/utc-cuip-video-event-producer/issues/3)
