### ISSUE TITLE
Cars reassigned ID's partway through the intersection

### ISSUE THREAD

**Issue by ambroxer** [UTC-SCAL/SCAL-Infrastructure#6]
**Describe the bug**
Sometimes, cars that pass through the intersection, typically traveling from east to west (left to right) along MLK will be reassigned ID's as they get closer to the camera. This happens even if the previous ID was given to it when it was in 3/4 profile midway through the intersection and can easily be kept track of.

**Scenario**
The silver car to the right is passing through the intersection, without turning, and is reassigned an ID after briefly being untagged, as seen in the screenshot.

**Expected behavior**
The car should be tracked through the entirety of its presence in the camera feed with a single tag.

**Screenshots**

![image](https://user-images.githubusercontent.com/48224792/53848888-085c2400-3f84-11e9-9280-95828f7299cc.png)

**Comment by oitsjustjose** [comment]
Moved to [here](https://github.com/ut-cuip/utc-cuip-video-event-producer/issues/2)
