### ISSUE TITLE
Peeples Street Camera Does Not Track Properly

### ISSUE THREAD

**Issue by ambroxer** [UTC-SCAL/SCAL-Infrastructure#7]
**Describe the bug**
Not necessarily a bug, but the camera may not be positioned properly to track cars throughout the intersection.

**Scenario**
Night-time, cars travelling towards the right side of the camera's view will only be registered and assigned IDs after crossing the intersection fully.

**Expected behavior**
Cars need to be tracked across the entire view of the camera. The camera is positioned too low to give the tracker any helpful information for tracking.

**Screenshots**
The car shown here did not get an ID until it had almost reached the edge of the camera's view. This keeps occurring with almost all cars travelling in the same direction as the car shown.
![image](https://user-images.githubusercontent.com/48224792/54729000-50b83c00-4b57-11e9-802a-05246b90f90b.png)

Although blurry, the bike shown in the bottom right of the photo was not assigned an ID at all while in full view of the camera.
![image](https://user-images.githubusercontent.com/48224792/54729093-f4095100-4b57-11e9-8650-8749b8629fe9.png)

**Comment by oitsjustjose** [comment]
Moved to [here](https://github.com/ut-cuip/utc-cuip-video-event-producer/issues/1)

**Comment by acedrew** [comment]
Hmmm we've got a number of positions that could be optimized after a little time with them. Would it be possible for you to check out all of the cameras and provide recommendations? Our main contact at the city was out this week but I can pick this up with him next week.
